---
#Redstone drop ratio of 100 (%)
RsDropRatio: 30%
RsCanPickup: false
SpecificItems:
  enabled: false
  items: ["Diamond Sword", "Diamond Axe"]

SpecificWorlds:
  enabled: false
  worlds: ["World"]
...
